language: node_js

node_js: 
   - "6.9.4"
script: 
   - echo 'Ready'
branches:
  only:
    - master
install:
   - npm install -g firebase-tools
after_success:
   - firebase use travis-testing-c9df4
   - firebase deploy --token $FIREBASE_DEPLOY_TOKEN

